Repository pyxem/diffsims, pull requests merged in 2020-09, with the labels that each got.

#102 bugfix for calculate_profile_data
  diffsims/generators/diffraction_generator.py
  diffsims/sims/diffraction_simulation.py
  diffsims/tests/test_sims/test_diffraction_simulation.py
  diffsims/tests/test_utils/test_sim_utils.py
  diffsims/utils/sim_utils.py
Labels: bug

#114 Small simulator improvements for v0.3
  diffsims/generators/diffraction_generator.py
  diffsims/sims/diffraction_simulation.py
  diffsims/tests/conftest.py
  diffsims/tests/test_generators/test_diffraction_generator.py
  diffsims/tests/test_generators/test_library_generator.py
  diffsims/tests/test_library/test_diffraction_library.py
  diffsims/tests/test_sims/test_diffraction_simulation.py
  diffsims/tests/test_utils/test_sim_utils.py
  diffsims/utils/sim_utils.py
Labels: dev, enhancement

#111 Add ReciprocalLatticePoint class storing structure, Miller indices and related quantities
  diffsims/__init__.py
  diffsims/crystallography/__init__.py
  diffsims/crystallography/reciprocal_lattice_point.py
  diffsims/release_info.py
  diffsims/structure_factor/__init__.py
  diffsims/structure_factor/atomic_scattering_factor.py
  diffsims/structure_factor/atomic_scattering_parameters.py
  diffsims/structure_factor/structure_factor.py
  diffsims/tests/conftest.py
  diffsims/tests/test_crystallography/__init__.py
  diffsims/tests/test_crystallography/test_reciprocal_lattice_point.py
  diffsims/tests/test_structure_factor/__init__.py
  diffsims/tests/test_structure_factor/test_atomic_scattering_factor.py
  diffsims/tests/test_structure_factor/test_atomic_scattering_parameter.py
  diffsims/tests/test_structure_factor/test_structure_factor.py
Labels: enhancement

#122 Adds a changelog
  CHANGELOG.md
  diffsims/release_info.py
Labels: enhancement
