Repository pyxem/diffsims, pull requests merged in 2020-12, with the labels that each got.

#147 Fix Coveralls reporting from GitHub Actions
  .github/workflows/build.yml
Labels: dev

#145 Make ReciprocalLatticePoint handle having only one point/vector
  .gitignore
  CHANGELOG.md
  diffsims/crystallography/reciprocal_lattice_point.py
  diffsims/tests/test_crystallography/test_reciprocal_lattice_point.py
Labels: bug

#142 added random sphere mesh generator
  diffsims/generators/rotation_list_generators.py
  diffsims/generators/sphere_mesh_generators.py
  diffsims/tests/test_generators/test_rotation_list_generator.py
  diffsims/tests/test_generators/test_sphere_mesh_generators.py
Labels: enhancement

#117 Add ring pattern generator
  diffsims/tests/test_utils/test_ring_pattern_utils.py
  diffsims/utils/ring_pattern_utils.py
Labels: enhancement
